package gendocs

// v2FieldDescriptions documents v2 / app fields by name, from the Notion
// reference. Fields shared with v1 fall back to the v1 description index.
var v2FieldDescriptions = map[string]string{
	// envelopes
	"product_feeds":           "Product feeds, one per platform.",
	"affiliate_vendor_orders": "Affiliate vendor orders.",
	"products":                "Products.",
	"total_count":             "Total number of matching products.",
	"total_pages":             "Total number of pages for the given `limit`.",
	"shop_info":               "The shop.",
	"shop_add_on":             "The app installation on this shop.",
	"failed_orders":           "Orders that could not be shipped, with the reason.",
	"fulfillments":            "Fulfillments created for the orders that succeeded.",
	"menus":                   "Menus.",
	// product feeds
	"mime_type": "MIME type of the feed (`text/csv`, `text/xml`, `application/json`).",
	// affiliate
	"status_code":                  "Attribution status, e.g. `create_succeed`.",
	"uid":                          "The affiliate user id (`uid` query parameter of the storefront visit).",
	"cid":                          "The affiliate campaign id (`cid` query parameter of the storefront visit).",
	"vendor_name":                  "The affiliate vendor name.",
	"order":                        "The attributed order.",
	"customer_id":                  "Customer id.",
	"subtotal_price":               "Subtotal before shipping.",
	"order_number":                 "Order number (integer).",
	"order_name":                   "Order name, `#` followed by the order number.",
	"buyer":                        "The buying customer's contact.",
	"line_items":                   "Ordered items.",
	"shipping_type":                "Shipping type code.",
	"shipping_name":                "Shipping method name.",
	"delivery_date":                "Requested delivery date.",
	"delivery_time":                "Requested delivery time slot (0 = any).",
	"delegate":                     "Staff account that placed the order on the customer's behalf.",
	"prices":                       "Price breakdown.",
	"transaction_number":           "Third-party payment transaction number.",
	"merchant_trade_no":            "Merchant trade number sent to the payment gateway.",
	"statuses":                     "Status fields; see the enums.",
	"timings":                      "Status timestamps.",
	"return_histories":             "Refund history.",
	"note":                         "Note.",
	"total_bonus_redemption_price": "Total bonus points redeemed in the bonus mall.",
	"linked_order_info":            "Affiliate / linked-order attribution.",
	"source":                       "Attribution source.",
	"shipping_status":              "Carrier shipping status.",
	"extra_info":                   "Extra information.",
	"from_device":                  "Device the order was placed from.",
	// line item
	"product_id":                   "Product id.",
	"product_variant_id":           "Product variant id.",
	"variant_title":                "Variant name.",
	"sku":                          "SKU.",
	"qc":                           "Vendor item code.",
	"vendor":                       "Vendor.",
	"price":                        "Unit price.",
	"cost":                         "Unit cost.",
	"quantity":                     "Quantity.",
	"item_type":                    "Item type, e.g. `normal`.",
	"discount_name":                "Discount name.",
	"discounts":                    "Itemised discounts.",
	"total_price_before_discounts": "Line total before discounts.",
	"total_discount":               "Line discount total.",
	"total_price_after_discounts":  "Line total after discounts.",
	"bonus_redemption_price":       "Bonus points redeemed for this item; null when not a bonus redemption.",
	"related_items":                "Bundle contents for combo products.",
	// prices
	"total_line_items_price":      "Sum of line items.",
	"shipping_rate_price":         "Shipping fee.",
	"total_price":                 "Order total.",
	"special_collection_discount": "Special collection (campaign) discount.",
	"vip_discount":                "VIP discount.",
	"shop_discount":               "Shop-wide discount detail.",
	"coupon_discount":             "Coupon detail (single, deprecated).",
	"coupon_discounts":            "Coupon details.",
	"bonus_consumed":              "Bonus points spent.",
	"vip_shipping_discount":       "VIP shipping discount.",
	"coupon_shipping_discount":    "Free-shipping coupon discount.",
	"price_discount":              "Manual (store manager) discount.",
	// timings
	"request_return_at": "Return requested at.",
	"return_at":         "Returned at.",
	"refund_at":         "Refunded at.",
	"closed_at":         "Closed at.",
	"cancelled_at":      "Cancelled at.",
	"expired_at":        "Pickup expired at.",
	"confirmed_at":      "Confirmed at.",
	// page
	"title":           "Title.",
	"handle":          "URL handle.",
	"status":          "Status.",
	"html_infos":      "Page HTML sections as a JSON **string** mapping section id to section content; parse it to get `{section_id: section_content}`.",
	"created_at":      "Created at.",
	"updated_at":      "Updated at.",
	"section_id":      "Custom HTML section id, e.g. `1714492800_app_store_api`.",
	"section_content": "Custom HTML section content as a JSON string: unicode-escape the HTML first, then JSON-encode it.",
	// cvs
	"measurement":       "Package volume size, `S60` or `S105`; required for Hi-Life and FamilyMart cold chain.",
	"size":              "Package size: `60` / `90` / `105` for T-cat quick store delivery; `60` / `90` / `120` / `150` for home delivery.",
	"tracking_company":  "Carrier code.",
	"cvs_shipping_type": "CVS shipping type, e.g. `family_c2c`; null when the order is not a CVS shipment.",
	"tracking_number":   "Carrier tracking number.",
	"fulfilled_at":      "Shipped at.",
	"received_at":       "Received at.",
	"fulfillment_ids":   "Fulfillment ids to print.",
	"fridge_or_frozen":  "`none`, `fridge` or `frozen`; not supported by `sf` and `hct`.",
	"is_fragile":        "Fragile flag; not supported by `sf` and `hct`.",
	"temperature":       "`normal` or `cold`.",
	"use_transfer":      "Prefer transferable tracking numbers; not supported by `sf` and `hct`.",
	"shipping_orders":   "Orders and line items to ship.",
	"order_id":          "Order id.",
	"line_item_ids":     "Line item ids of the order to include.",
	"message":           "Message.",
	"print_type":        "HCT only: `normal` or `thermal`.",
	"order_ids":         "Order ids to print (batch only).",
	// menus
	"system_default": "Whether the menu is a system default menu.",
	"items":          "Child items (recursive).",
	"subject_handle": "Handle of the linked subject (product, page, collection), when any.",
	"url":            "Link URL.",
	"position":       "Position (1-based).",
	"subtitle":       "Subtitle.",
	"icon_image_url": "Icon image URL.",
	"level":          "Nesting level (1 = top).",
	// categories / collections
	"full_handle":         "Full URL path including every parent handle, e.g. `clothing/mens/shirts`.",
	"published":           "Whether it is published.",
	"body_html":           "HTML description.",
	"products_order_name": "Display label of the product ordering used in the storefront.",
	"rules":               "Automatic filter rules.",
	"filter":              "Human-readable rule, e.g. `商品價格 小於 1000`.",
	// customers
	"ids":            "Customer ids.",
	"include_params": "Extra sections to include.",
	"provider":       "OAuth provider, e.g. `line`, `facebook`.",
	"provider_type":  "Provider type: `line`, `line_at`, `facebook`, ... (on `uid_providers` entries; the lookup parameter is `provider`).",
	"vip_info":       "VIP information (with `include_params=vip_info`).",
	"current_group":  "Current VIP group.",
	"current_level":  "Current VIP level.",
	"next_level":     "Next VIP level.",
	"start_at":       "Valid from.",
	"end_at":         "Valid until.",
	"difference_of_total_spent_in_validity_days_for_renewal": "Spend still needed within the validity period to renew.",
	"difference_of_total_spent_for_renewal":                  "Single-order spend still needed to renew.",
	"difference_of_total_spent_in_validity_days_for_upgrade": "Spend still needed within the validity period to upgrade.",
	"difference_of_total_spent_for_upgrade":                  "Single-order spend still needed to upgrade.",
	// shop emails
	"shop_email": "The shop's e-mail address.",
	"subscribes": "Addresses subscribed to shop notifications.",
	// product search
	"q":                   "Search text (fuzzy match on the product name).",
	"limit":               "Maximum number of results.",
	"offset":              "Start index.",
	"filter_published":    "Only published products (default true); `false` includes unpublished ones.",
	"vendors":             "Vendor filter.",
	"product_types":       "Product type filter.",
	"tags":                "Tag filter.",
	"store_types":         "Store type filter: `1` EC, `2` POS, `4` branch store.",
	"filter_branch_store": "Only branch-store products.",
	"filter_on_sell":      "Only products currently on sale.",
	"exclude_tags":        "Tags to exclude.",
	"skus":                "SKU filter (custom feature).",
	"branch_stores":       "Branch store ids (custom feature).",
	"store_nos":           "Branch store numbers (custom feature).",
	"photo_urls":          "Photo URLs.",
	"seo_meta_tags":       "SEO meta tags.",
	"temperature_types":   "Temperature zones, e.g. `常溫`.",
	// inventory
	"store_number":       "Branch store number.",
	"inventory_quantity": "Inventory quantity to set.",
	"job_id":             "Job id.",
	"total_items":        "Number of items in the job.",
	"completed_at":       "Completed at.",
	"result":             "Job result once finished.",
	"total":              "Items processed.",
	"succeeded":          "Items updated.",
	"failed":             "Items that failed.",
	"failed_items":       "Failed items with the reason.",
	"error":              "Error.",
	// wallet
	"balance":             "Wallet balance in TWD.",
	"currency":            "Currency; currently always `TWD`.",
	"type":                "Transaction type: `topup`, `consumption`, `refund`, `cancel_order`, `bonus`.",
	"amount":              "Amount; positive increases the balance (top-up, cancelled order), negative decreases it (consumption, refund).",
	"balance_after":       "Balance after this transaction.",
	"payment_name":        "Payment method name (e.g. `現金`); only for `topup` and `refund`.",
	"invalid_einvoices":   "Voided e-invoices (`refund` only).",
	"allowance_einvoices": "Allowance e-invoices (`refund` only).",
	"einvoice":            "E-invoice of the top-up (`topup` only).",
	"paper_invoice_no":    "Paper invoice number when `invoice_type` is `paper_invoice`.",
	"company_no":          "Tax id on the invoice.",
	"invoice_no":          "E-invoice number; null for paper or not issued.",
	"invoice_at":          "Issued at.",
	"invalid_at":          "Voided at.",
	"random_num":          "Random code.",
	"love_code":           "Donation code.",
	"phone_barcode":       "Mobile barcode carrier.",
	"nature_person":       "Citizen digital certificate carrier.",
	// shop / settings
	"primary_domain":     "The shop's primary domain.",
	"og_image_url":       "Open Graph image URL.",
	"shop_line_chat_bot": "LINE chat bot settings (`bot_id`), null when not configured.",
	"shop_line":          "LINE login / LIFF settings.",
	"login_enable":       "Whether LINE login is enabled.",
	"liff_id":            "LIFF app id.",
	"liff_enable":        "Whether LIFF is enabled.",
	"language":           "Storefront language, e.g. `zh-TW`.",
	"sms_prefix":         "Prefix prepended to SMS messages.",
	"merchant_location":  "Merchant location.",
	"market_location":    "Market location.",
	"settings":           "The app's setting values keyed by field name (as declared in the manifest `setting_fields`); for `PUT /settings`, the list of `{field, data}` pairs to set.",
	"vendor_type":        "App vendor name.",
	"token":              "The app installation token.",
	"add_on_version":     "The installed app version.",
	"webhook_url":        "Webhook endpoint the app registered.",
	"manifest":           "The app manifest.",
	"manifest_version":   "Manifest version.",
	"version":            "App version.",
	"scopes":             "Granted scopes, space-separated.",
	"webhook_events":     "Events the app subscribed to.",
	"embedded":           "Whether the app is embedded in the admin.",
	"field":              "Setting field name as declared in the manifest.",
	"data":               "Setting value.",
	"name":               "Name.",
	"email":              "E-mail address.",
	"id":                 "Id.",
}
