package gendocs

// webhookEvent describes one Event: its English meaning and the payload
// object (section of the reference) CYBERBIZ posts for it.
type webhookEvent struct {
	Code        string
	Description string
	Payload     string // section name in webhookSource
}

// webhookEvents are the documented events in reference order. The Cart
// payload (reference section 6) has no event name in any source under
// docs/references/, so no cart event is listed; see whCartNote.
var webhookEvents = []webhookEvent{
	{"customers/create", "A customer registered.", "Customer"},
	{"customers/update", "A customer's profile changed.", "Customer"},
	{"uid_providers/create", "A social-login uid was linked to a customer (the reference documents no separate payload; the Customer object is posted).", "Customer"},
	{"uid_providers/update", "A social-login uid of a customer changed (Customer object).", "Customer"},
	{"bonus_points/create", "Bonus points were granted.", "Bonus Points"},
	{"bonus_points/update", "Bonus points were used.", "Bonus Points"},
	{"bonus_points/destroy", "A bonus point record was deleted.", "Bonus Points"},
	{"comment_bonus/create", "Bonus points were granted for an approved product review.", "Bonus Points"},
	{"orders/create", "An order was placed.", "Order"},
	{"orders/paid", "An order was paid.", "Order"},
	{"orders/preparing", "An order is being prepared for shipment.", "Order"},
	{"orders/fulfilled", "An order was shipped.", "Order"},
	{"orders/received", "An order was received by the customer.", "Order"},
	{"orders/arrived", "An order arrived at the pickup store.", "Order"},
	{"orders/expired", "An order was not picked up in time.", "Order"},
	{"orders/cancelled", "An order was cancelled.", "Order"},
	{"orders/returned", "An order was returned.", "Order"},
	{"orders/partial_return", "Part of an order was returned.", "Order"},
	{"orders/refunded", "An order was refunded.", "Order"},
	{"orders/partial_refunded", "Part of an order was refunded.", "Order"},
	{"orders/closed", "An order was closed.", "Order"},
	{"orders/request_return", "The customer requested a return.", "Order"},
	{"orders/opened", "An order was (re)opened.", "Order"},
	{"express_delivery_orders/update", "An express-delivery order changed.", "Order"},
	{"products/create", "A product was created.", "Product"},
	{"products/update", "A product changed.", "Product"},
	{"products/delete", "A product was deleted.", "Product"},
	{"variants/create", "A product variant was created.", "Product Variant"},
	{"variants/update", "A product variant changed.", "Product Variant"},
	{"variants/delete", "A product variant was deleted.", "Product Variant"},
	{"coupons/create", "A coupon was created.", "Coupon"},
	{"coupons/update", "A coupon was used.", "Coupon"},
	{"coupons/destroy", "A coupon was deleted.", "Coupon"},
	{"customer_vip_level/update", "A customer's VIP level changed.", "Customer VIP Level"},
	{"apps/uninstall", "The app was uninstalled from the shop.", "App Uninstall"},
}

// undocumentedEvents appear in app manifests (Golden File GET /settings)
// but have no payload documentation.
var undocumentedEvents = []string{
	"customer_tags/update",
	"affiliate_vendor_orders/create",
	"affiliate_vendor_orders/closed",
	"affiliate_vendor_orders/cancelled",
	"orders/update",
	"products/update_photos",
	"products/update_options",
	"domains/create",
	"domains/update",
	"domains/destroy",
	"collections/create",
	"collections/update",
	"collections/delete",
	"bulk_operations/finish",
	"menus/create",
	"menus/update",
	"menus/destroy",
}

// webhookSectionByKey maps a payload field to the reference section that
// describes its object. Context-specific cases are keyed "Parent/field".
var webhookSectionByKey = map[string]string{
	"Order/customer":                "Customer",
	"Cart/customer":                 "Customer",
	"buyer":                         "Buyer",
	"receiver":                      "Receiver",
	"billing_address":               "Receiver",
	"line_items":                    "Line Item",
	"Exchange Histories/line_items": "Exchange Line Item",
	"shipping_vendor":               "Shipping Vendor",
	"fulfillments":                  "Fulfillment",
	"multiple_payment_infos":        "Multiple Payment Info",
	"prices":                        "Prices",
	"einvoice":                      "E-Invoice",
	"statuses":                      "Statuses",
	"timings":                       "Timings",
	"return_histories":              "Return History",
	"branch_store":                  "Branch Store",
	"express_delivery_branch_store": "Branch Store",
	"pos_info":                      "POS Info",
	"exchange_histories":            "Exchange Histories",
	"linked_order_info":             "Linked Order Info",
	"customer_cancel_reason_detail": "Customer Cancel Reason Detail",
	"Customer/tags":                 "Customer Tag",
	"Order/tags":                    "Customer Tag",
	"Product/tags":                  "Product Tag",
	"address":                       "Customer Address",
	"detail_address":                "Detail Address",
	"custom_fields":                 "Custom Field",
	"uid_providers":                 "UID Providers",
	"Line Item/discounts":           "Discount",
	"Prices/discounts":              "Discounts Detail",
	"related_items":                 "Related Items",
	"Related Items/items":           "Combo Item",
	"shop_discount":                 "Shop Discount",
	"coupon_discount":               "Coupon Discount",
	"coupon_discounts":              "Coupon Discount",
	"shipping_rates":                "Shipping Rate",
	"payments":                      "Payment",
	"custom_collections":            "Custom Collection",
	"related_collections":           "Custom Collection",
	"special_collection":            "Special Collection",
	"product_variants":              "Product Variant",
	"product_options":               "Product Option",
	"photos":                        "Product Photo",
	"channel":                       "Channel",
	"pim_infos":                     "PIM Info",
	"cart_add_items":                "Cart Add Item",
	"variant":                       "Product Variant",
	"current_group":                 "Current VIP Group",
	"current_level":                 "VIP Level",
	"next_level":                    "VIP Level",
	"vip_group_levels":              "VIP Level",
	"Customer VIP Level/extra_info": "Extra Info",
	"birth_gift_setting":            "Gift Setting",
	"upgrade_gift_setting":          "Gift Setting",
	"Gift Setting/bonus":            "Bonus Setting",
	"Gift Setting/coupon":           "Coupon Setting",
	"presets":                       "Coupon Presets",
	"special_collection_type":       "Special Collection Type",
	"type_rules":                    "Type Rules",
}
